export const AJAX_CALL = 'AJAX_CALL';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const AJAX_FAILED = 'AJAX_FAILED';
export const AJAX_FINISHED = 'AJAX_FINISHED';
export const AJAX_LOADING_RESET = 'AJAX_LOADING_RESET';

export const CHECK_AUTHORIZATION = 'CHECK_AUTHORIZATION';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_CONTINUE = 'REGISTER_CONTINUE';

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const CONFIRM_SIGN_UP = "CONFIRM_SIGN_UP";
export const CONFIRM_SIGN_UP_SUCCESS = "CONFIRM_SIGN_UP_SUCCESS";

export const CHANGE_USER_PWD = "CHANGE_USER_PWD";
export const CHANGE_USER_PWD_SUCCESS = "CHANGE_USER_PWD_SUCCESS";

export const FORGOT_USER_PWD = "FORGOT_USER_PWD";
export const FORGOT_USER_PWD_SUCCESS = "FORGOT_USER_PWD_SUCCESS";

export const RESEND_SIGN_UP_CODE = "RESEND_SIGN_UP_CODE";
export const RESEND_SIGN_UP_CODE_SUCCESS = "RESEND_SIGN_UP_CODE_SUCCESS";

export const LOAD_AUTHORITIES_REQUEST  = "LOAD_AUTHORITIES_REQUEST";
export const LOAD_AUTHORITIES_SUCCESS  = "LOAD_AUTHORITIES_SUCCESS";
export const LOAD_AUTHORITIES_FAILED = "LOAD_AUTHORITIES_FAILED";

export const LOAD_AUTHORITY_REQUEST  = "LOAD_AUTHORITY_REQUEST";
export const LOAD_AUTHORITY_SUCCESS  = "LOAD_AUTHORITY_SUCCESS";
export const LOAD_AUTHORITY_FAILED = "LOAD_AUTHORITY_FAILED";

export const CREATE_USER_REQUEST  = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS  = "CREATE_USER_SUCCESS";

export const UPDATE_USER_REQUEST  = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS  = "UPDATE_USER_SUCCESS";

export const REACTIVATE_USER_REQUEST  = "REACTIVATE_USER_REQUEST";
export const REACTIVATE_USER_SUCCESS  = "REACTIVATE_USER_SUCCESS";

export const RENEW_CODE_USER_REQUEST  = "RENEW_CODE_USER_REQUEST";
export const RENEW_CODE_USER_SUCCESS  = "RENEW_CODE_USER_SUCCESS";

export const DELETE_USER_REQUEST  = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS  = "DELETE_USER_SUCCESS";

export const LOAD_USERS_SIMPLE_REQUEST  = "LOAD_USERS_SIMPLE_REQUEST";
export const LOAD_USERS_SIMPLE_SUCCESS  = "LOAD_USERS_SIMPLE_SUCCESS";

export const LOAD_USERS_REQUEST  = "LOAD_USERS_REQUEST";
export const LOAD_USERS_SUCCESS  = "LOAD_USERS_SUCCESS";

export const LOAD_USERS_PAGINATION_REQUEST  = "LOAD_USERS_PAGINATION_REQUEST";
export const LOAD_USERS_PAGINATION_SUCCESS  = "LOAD_USERS_PAGINATION_SUCCESS";

export const LOAD_USER_REQUEST  = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS  = "LOAD_USER_SUCCESS";

export const USERS_ROWS_PER_PAGE_UPDATE  = "USERS_ROWS_PER_PAGE_UPDATE";
export const FILTER_USER_SUBDIVISIONS_UPDATE  = "FILTER_USER_SUBDIVISIONS_UPDATE";
export const FILTER_USER_DEPARTMENTS_UPDATE  = "FILTER_USER_DEPARTMENTS_UPDATE";
export const FILTER_USER_COMPANIES_UPDATE  = "FILTER_USER_COMPANIES_UPDATE";
export const FILTER_USER_ROLES_UPDATE  = "FILTER_USER_ROLES_UPDATE";
export const FILTER_USER_SHOW_DEACTIVATED_UPDATE  = "FILTER_USER_SHOW_DEACTIVATED_UPDATE";
export const FILTER_USER_SEARCH_UPDATE  = "FILTER_USER_SEARCH_UPDATE";
export const FILTER_USER_CLEAR  = "FILTER_USER_CLEAR";

export const CREATE_USER_ROLE_REQUEST  = "CREATE_USER_ROLE_REQUEST";
export const CREATE_USER_ROLE_SUCCESS  = "CREATE_USER_ROLE_SUCCESS";
export const CREATE_USER_ROLE_FAILED = "CREATE_USER_ROLE_FAILED";

export const DELETE_USER_ROLE_REQUEST  = "DELETE_USER_ROLE_REQUEST";
export const DELETE_USER_ROLE_SUCCESS  = "DELETE_USER_ROLE_SUCCESS";
export const DELETE_USER_ROLE_FAILED = "DELETE_USER_ROLE_FAILED";

export const UPDATE_USER_ROLE_REQUEST  = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS  = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAILED = "UPDATE_USER_ROLE_FAILED";

export const LOAD_USER_ROLES_REQUEST  = "LOAD_USER_ROLES_REQUEST";
export const LOAD_USER_ROLES_SUCCESS  = "LOAD_USER_ROLES_SUCCESS";
export const LOAD_USER_ROLES_FAILED = "LOAD_USER_ROLES_FAILED";

export const LOAD_USER_ROLES_PAGINATION_REQUEST  = "LOAD_USER_ROLES_PAGINATION_REQUEST";
export const LOAD_USER_ROLES_PAGINATION_SUCCESS  = "LOAD_USER_ROLES_PAGINATION_SUCCESS";

export const LOAD_USER_ROLE_REQUEST  = "LOAD_USER_ROLE_REQUEST";
export const LOAD_USER_ROLE_SUCCESS  = "LOAD_USER_ROLE_SUCCESS";
export const LOAD_USER_ROLE_FAILED = "LOAD_USER_ROLE_FAILED";


export const CREATE_USER_GROUP_REQUEST  = "CREATE_USER_GROUP_REQUEST";
export const CREATE_USER_GROUP_SUCCESS  = "CREATE_USER_GROUP_SUCCESS";
export const CREATE_USER_GROUP_FAILED = "CREATE_USER_GROUP_FAILED";

export const DELETE_USER_GROUP_REQUEST  = "DELETE_USER_GROUP_REQUEST";
export const DELETE_USER_GROUP_SUCCESS  = "DELETE_USER_GROUP_SUCCESS";
export const DELETE_USER_GROUP_FAILED = "DELETE_USER_GROUP_FAILED";

export const UPDATE_USER_GROUP_REQUEST  = "UPDATE_USER_GROUP_REQUEST";
export const UPDATE_USER_GROUP_SUCCESS  = "UPDATE_USER_GROUP_SUCCESS";
export const UPDATE_USER_GROUP_FAILED = "UPDATE_USER_GROUP_FAILED";

export const LOAD_USER_GROUPS_REQUEST  = "LOAD_USER_GROUPS_REQUEST";
export const LOAD_USER_GROUPS_SUCCESS  = "LOAD_USER_GROUPS_SUCCESS";
export const LOAD_USER_GROUPS_FAILED = "LOAD_USER_GROUPS_FAILED";

export const LOAD_USER_GROUPS_PAGINATION_REQUEST  = "LOAD_USER_GROUPS_PAGINATION_REQUEST";
export const LOAD_USER_GROUPS_PAGINATION_SUCCESS  = "LOAD_USER_GROUPS_PAGINATION_SUCCESS";

export const LOAD_USER_GROUP_REQUEST  = "LOAD_USER_GROUP_REQUEST";
export const LOAD_USER_GROUP_SUCCESS  = "LOAD_USER_GROUP_SUCCESS";
export const LOAD_USER_GROUP_FAILED = "LOAD_USER_GROUP_FAILED";

export const FILTER_SUPPORT_CENTER_STATUS_UPDATE  = "FILTER_SUPPORT_CENTER_STATUS_UPDATE";
export const FILTER_SUPPORT_CENTER_START_DATE_UPDATE  = "FILTER_SUPPORT_CENTER_START_DATE_UPDATE";
export const FILTER_SUPPORT_CENTER_END_DATE_UPDATE  = "FILTER_SUPPORT_CENTER_END_DATE_UPDATE";
export const FILTER_SUPPORT_CENTER_CLEAR  = "FILTER_SUPPORT_CENTER_CLEAR";

export const LOAD_SUPPORT_CENTER_ALL_REQUEST  = "LOAD_SUPPORT_CENTER_ALL_REQUEST";
export const LOAD_SUPPORT_CENTER_ALL_SUCCESS  = "LOAD_SUPPORT_CENTER_ALL_SUCCESS";
export const LOAD_SUPPORT_CENTER_ALL_FAILED = "LOAD_SUPPORT_CENTER_ALL_FAILED";

export const LOAD_SUPPORT_CENTER_REQUEST  = "LOAD_SUPPORT_CENTER_REQUEST";
export const LOAD_SUPPORT_CENTER_SUCCESS  = "LOAD_SUPPORT_CENTER_SUCCESS";
export const LOAD_SUPPORT_CENTER_FAILED = "LOAD_SUPPORT_CENTER_FAILED";

export const CREATE_SUPPORT_CENTER_REQUEST  = "CREATE_SUPPORT_CENTER_REQUEST";
export const CREATE_SUPPORT_CENTER_SUCCESS  = "CREATE_SUPPORT_CENTER_SUCCESS";
export const CREATE_SUPPORT_CENTER_FAILED = "CREATE_SUPPORT_CENTER_FAILED";

export const ADD_COMMENT_SUPPORT_CENTER_REQUEST  = "ADD_COMMENT_SUPPORT_CENTER_REQUEST";
export const ADD_COMMENT_SUPPORT_CENTER_SUCCESS  = "ADD_COMMENT_SUPPORT_CENTER_SUCCESS";
export const ADD_COMMENT_SUPPORT_CENTER_FAILED = "ADD_COMMENT_SUPPORT_CENTER_FAILED";

export const UPDATE_SUPPORT_CENTER_REQUEST  = "UPDATE_SUPPORT_CENTER_REQUEST";
export const UPDATE_SUPPORT_CENTER_SUCCESS  = "UPDATE_SUPPORT_CENTER_SUCCESS";
export const UPDATE_SUPPORT_CENTER_FAILED = "UPDATE_SUPPORT_CENTER_FAILED";

export const LOAD_SUPPORT_CENTER_MODULES_REQUEST  = "LOAD_SUPPORT_CENTER_MODULES_REQUEST";
export const LOAD_SUPPORT_CENTER_MODULES_SUCCESS  = "LOAD_SUPPORT_CENTER_MODULES_SUCCESS";
export const LOAD_SUPPORT_CENTER_MODULES_FAILED = "LOAD_SUPPORT_CENTER_MODULES_FAILED";

export const LOAD_SUPPORT_CENTER_LEVELS_REQUEST  = "LOAD_SUPPORT_CENTER_LEVELS_REQUEST";
export const LOAD_SUPPORT_CENTER_LEVELS_SUCCESS  = "LOAD_SUPPORT_CENTER_LEVELS_SUCCESS";
export const LOAD_SUPPORT_CENTER_LEVELS_FAILED = "LOAD_SUPPORT_CENTER_LEVELS_FAILED";

export const LOAD_SUPPORT_CENTER_STATUSES_REQUEST  = "LOAD_SUPPORT_CENTER_STATUSES_REQUEST";
export const LOAD_SUPPORT_CENTER_STATUSES_SUCCESS  = "LOAD_SUPPORT_CENTER_STATUSES_SUCCESS";
export const LOAD_SUPPORT_CENTER_STATUSES_FAILED = "LOAD_SUPPORT_CENTER_STATUSES_FAILED";

export const DOWNLOAD_SUPPORT_CENTER_ATTACHMENT  = "DOWNLOAD_SUPPORT_CENTER_ATTACHMENT";
export const CREATE_SUPPORT_CENTER_WITH_ATTACHMENTS  = "CREATE_SUPPORT_CENTER_WITH_ATTACHMENTS";
export const UPDATE_SUPPORT_CENTER_WITH_ATTACHMENTS  = "UPDATE_SUPPORT_CENTER_WITH_ATTACHMENTS";

export const LOAD_SOFTWARE_LOGS_REQUEST  = "LOAD_SOFTWARE_LOGS_REQUEST";
export const LOAD_SOFTWARE_LOGS_SUCCESS  = "LOAD_SOFTWARE_LOGS_SUCCESS";

export const CREATE_SOFTWARE_LOG_REQUEST  = "CREATE_SOFTWARE_LOG_REQUEST";

export const DOWNLOAD_FILE_PROGRESS_OPEN  = "DOWNLOAD_FILE_PROGRESS_OPEN";
export const DOWNLOAD_FILE_PROGRESS_CLOSE  = "DOWNLOAD_FILE_PROGRESS_CLOSE";
export const DOWNLOAD_FILE_PROGRESS  = "DOWNLOAD_FILE_PROGRESS";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const ACTIVATE_LANG_MODAL = "ACTIVATE_LANG_MODAL";

export const LOAD_ALL_CLIENTS_REQUEST = "LOAD_ALL_CLIENTS_REQUEST";
export const LOAD_ALL_CLIENTS_SUCCESS = "LOAD_ALL_CLIENTS_SUCCESS";

export const LOAD_CLIENTS_PAGINATION_REQUEST  = "LOAD_CLIENTS_PAGINATION_REQUEST";
export const LOAD_CLIENTS_PAGINATION_SUCCESS  = "LOAD_CLIENTS_PAGINATION_SUCCESS";

export const FILTER_CLIENT_SEARCH_UPDATE = "FILTER_CLIENT_SEARCH_UPDATE";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";

// VERSION MOBILE
export const LOAD_ALL_VERSIONS_MOBILE_REQUEST = "LOAD_ALL_VERSIONS_MOBILE_REQUEST";
export const LOAD_ALL_VERSIONS_MOBILE_SUCCESS = "LOAD_ALL_VERSIONS_MOBILE_SUCCESS";

export const FILTER_VERSION_MOBILE_SEARCH_UPDATE = "FILTER_VERSION_MOBILE_SEARCH_UPDATE";

export const CREATE_VERSION_MOBILE_REQUEST = "CREATE_VERSION_MOBILE_REQUEST";
export const CREATE_VERSION_MOBILE_SUCCESS = "CREATE_VERSION_MOBILE_SUCCESS";

export const UPDATE_VERSION_MOBILE_REQUEST = "UPDATE_VERSION_MOBILE_REQUEST";
export const UPDATE_VERSION_MOBILE_SUCCESS = "UPDATE_VERSION_MOBILE_SUCCESS";

export const DELETE_VERSION_MOBILE_REQUEST = "DELETE_VERSION_MOBILE_REQUEST";
export const DELETE_VERSION_MOBILE_SUCCESS = "DELETE_VERSION_MOBILE_SUCCESS";

export const UPDATE_SOFTWARE_LOG_REQUEST = "UPDATE_SOFTWARE_LOG_REQUEST";

export const DELETE_SOFTWARE_LOG_REQUEST = "DELETE_SOFTWARE_LOG_REQUEST";
export const DELETE_SOFTWARE_LOG_SUCCESS = "DELETE_SOFTWARE_LOG_SUCCESS";

export const LOAD_SOFTWARE_LOGS_PAGINATION_REQUEST = "LOAD_SOFTWARE_LOGS_PAGINATION_REQUEST";
export const LOAD_SOFTWARE_LOGS_PAGINATION_SUCCESS = "LOAD_SOFTWARE_LOGS_PAGINATION_SUCCESS";

export const FILTER_SOFTWARE_LOG_SEARCH_UPDATE = "FILTER_SOFTWARE_LOG_SEARCH_UPDATE";
export const FILTER_CLIENTS_UPDATE = "FILTER_CLIENTS_UPDATE";
export const CLEAR_SOFTWARE_LOG_FILTERS = "CLEAR_SOFTWARE_LOG_FILTERS";

export const LOAD_ROADMAP_LOGS_REQUEST = "LOAD_ROADMAP_LOGS_REQUEST";
export const LOAD_ROADMAP_LOGS_SUCCESS = "LOAD_ROADMAP_LOGS_SUCCESS";
export const LOAD_ROADMAP_LOGS_FAILED = "LOAD_ROADMAP_LOGS_FAILED";

export const LOAD_ROADMAP_LOGS_PAGINATE_FILTER_REQUEST = "LOAD_ROADMAP_LOGS_PAGINATE_FILTER_REQUEST";
export const LOAD_ROADMAP_LOGS_PAGINATE_FILTER_SUCCESS = "LOAD_ROADMAP_LOGS_PAGINATE_FILTER_SUCCESS";
export const LOAD_ROADMAP_LOGS_PAGINATE_FILTER_FAILED = "LOAD_ROADMAP_LOGS_PAGINATE_FILTER_FAILED";

export const CREATE_ROADMAP_LOG_REQUEST = "CREATE_ROADMAP_LOG_REQUEST";
export const CREATE_ROADMAP_LOG_SUCCESS = "CREATE_ROADMAP_LOG_SUCCESS";
export const CREATE_ROADMAP_LOG_FAILED = "CREATE_ROADMAP_LOG_FAILED";

export const UPDATE_ROADMAP_LOG_REQUEST = "UPDATE_ROADMAP_LOG_REQUEST";
export const UPDATE_ROADMAP_LOG_SUCCESS = "UPDATE_ROADMAP_LOG_SUCCESS";
export const UPDATE_ROADMAP_LOG_FAILED = "UPDATE_ROADMAP_LOG_FAILED";

export const DELETE_ROADMAP_LOG_REQUEST = "DELETE_ROADMAP_LOG_REQUEST";
export const DELETE_ROADMAP_LOG_SUCCESS = "DELETE_ROADMAP_LOG_SUCCESS";
export const DELETE_ROADMAP_LOG_FAILED = "DELETE_ROADMAP_LOG_FAILED";

export const CLEAR_ROADMAP_LOG_FILTERS = "CLEAR_ROADMAP_LOG_FILTERS";
export const CHANGE_ROADMAP_LOG_FILTERS = "CHANGE_ROADMAP_LOG_FILTERS";

//ICARUS DOCS

export const LOAD_ICARUS_DOCUMENTATION_FILE_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILE_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILE_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILE_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FILE_FAILED = "LOAD_ICARUS_DOCUMENTATION_FILE_FAILED";

export const CREATE_ICARUS_DOCUMENTATION_FILE_DOWNLOAD_LIST_EXCEL_REQUEST  = "CREATE_ICARUS_DOCUMENTATION_FILE_DOWNLOAD_LIST_EXCEL_REQUEST";

export const LOAD_ICARUS_DOCUMENTATION_FILE_HISTORY_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILE_HISTORY_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILE_HISTORY_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILE_HISTORY_SUCCESS";

export const ICARUS_DOCUMENTATION_FILE_MOVE_REQUEST  = "ICARUS_DOCUMENTATION_FILE_MOVE_REQUEST";
export const ICARUS_DOCUMENTATION_FILE_MOVE_SUCCESS  = "ICARUS_DOCUMENTATION_FILE_MOVE_SUCCESS";

export const CREATE_ICARUS_DOCUMENTATION_FILE_REQUEST  = "CREATE_ICARUS_DOCUMENTATION_FILE_REQUEST";
export const CREATE_ICARUS_DOCUMENTATION_FILE_SUCCESS  = "CREATE_ICARUS_DOCUMENTATION_FILE_SUCCESS";
export const CREATE_ICARUS_DOCUMENTATION_FILE_FAILED = "CREATE_ICARUS_DOCUMENTATION_FILE_FAILED";

export const UPLOAD_ICARUS_DOCUMENTATION_FILE  = "UPLOAD_ICARUS_DOCUMENTATION_FILE";
export const UPLOAD_ICARUS_DOCUMENTATION_FILE_SUCCESS  = "UPLOAD_ICARUS_DOCUMENTATION_FILE_SUCCESS";

export const EDIT_ICARUS_DOCUMENTATION_FILE_FAILED  = "EDIT_ICARUS_DOCUMENTATION_FILE_FAILED";
export const PASS_ICARUS_DOCUMENTATION_FILE  = "PASS_ICARUS_DOCUMENTATION_FILE";
export const EDIT_ICARUS_DOCUMENTATION_FILE_REQUEST  = "EDIT_ICARUS_DOCUMENTATION_FILE_REQUEST";

export const DOWNLOAD_ICARUS_DOCUMENTATION_FILE  = "DOWNLOAD_ICARUS_DOCUMENTATION_FILE";

export const CANCEL_DOWNLOAD_ICARUS_DOCUMENTATION_FILE  = "CANCEL_DOWNLOAD_ICARUS_DOCUMENTATION_FILE";

export const VIEW_ICARUS_DOCUMENTATION_FILE  = "VIEW_ICARUS_DOCUMENTATION_FILE";
export const VIEW_ICARUS_DOCUMENTATION_FILE_SUCCESS  = "VIEW_ICARUS_DOCUMENTATION_FILE_SUCCESS";

export const CANCEL_VIEW_ICARUS_DOCUMENTATION_FILE  = "CANCEL_VIEW_ICARUS_DOCUMENTATION_FILE";

export const REVERSE_ICARUS_DOCUMENTATION_FILE_ORDER  = "REVERSE_ICARUS_DOCUMENTATION_FILE_ORDER";
export const REVERSE_ICARUS_DOCUMENTATION_FOLDER_ORDER  = "REVERSE_ICARUS_DOCUMENTATION_FOLDER_ORDER";

export const LOAD_ICARUS_DOCUMENTATION_FILES_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILES_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILES_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILES_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FILES_FAILED = "LOAD_ICARUS_DOCUMENTATION_FILES_FAILED";

export const DELETE_ICARUS_DOCUMENTATION_FILE_REQUEST  = "DELETE_ICARUS_DOCUMENTATION_FILE_REQUEST";
export const DELETE_ICARUS_DOCUMENTATION_FILE_SUCCESS  = "DELETE_ICARUS_DOCUMENTATION_FILE_SUCCESS";
export const DELETE_ICARUS_DOCUMENTATION_FILE_FAILED = "DELETE_ICARUS_DOCUMENTATION_FILE_FAILED";

export const ICARUS_DOCUMENTATION_FOLDER_MOVE_REQUEST  = "ICARUS_DOCUMENTATION_FOLDER_MOVE_REQUEST";
export const ICARUS_DOCUMENTATION_FOLDER_MOVE_SUCCESS  = "ICARUS_DOCUMENTATION_FOLDER_MOVE_SUCCESS";

export const LOAD_ICARUS_DOCUMENTATION_FOLDER_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FOLDER_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FOLDER_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FOLDER_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FOLDER_FAILED = "LOAD_ICARUS_DOCUMENTATION_FOLDER_FAILED";

export const CREATE_ICARUS_DOCUMENTATION_FOLDER_REQUEST  = "CREATE_ICARUS_DOCUMENTATION_FOLDER_REQUEST";
export const CREATE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS  = "CREATE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS";
export const CREATE_ICARUS_DOCUMENTATION_FOLDER_FAILED = "CREATE_ICARUS_DOCUMENTATION_FOLDER_FAILED";

export const UPDATE_ICARUS_DOCUMENTATION_FOLDER_REQUEST  = "UPDATE_ICARUS_DOCUMENTATION_FOLDER_REQUEST";
export const UPDATE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS  = "UPDATE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS";
export const UPDATE_ICARUS_DOCUMENTATION_FOLDER_FAILED = "UPDATE_ICARUS_DOCUMENTATION_FOLDER_FAILED";

export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_FAILED = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_FAILED";

export const LOAD_ICARUS_DOCUMENTATION_FOLDER_TREE_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FOLDER_TREE_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FOLDER_TREE_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FOLDER_TREE_SUCCESS";

export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_FAILED  = "LOAD_ICARUS_DOCUMENTATION_FOLDERS_ON_PATH_FAILED";

export const LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_FAILED  = "LOAD_ICARUS_DOCUMENTATION_FILES_IN_FOLDER_FAILED";

export const LOAD_ICARUS_DOCUMENTATION_FILES_BY_SEARCH_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILES_BY_SEARCH_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILES_BY_SEARCH_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILES_BY_SEARCH_SUCCESS";

export const LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_REQUEST  = "LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_REQUEST";
export const LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_SUCCESS  = "LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_SUCCESS";
export const LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_FAILED  = "LOAD_ICARUS_DOCUMENTATION_FILES_BY_FILTER_FAILED";

export const DELETE_ICARUS_DOCUMENTATION_FOLDER_REQUEST  = "DELETE_ICARUS_DOCUMENTATION_FOLDER_REQUEST";
export const DELETE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS  = "DELETE_ICARUS_DOCUMENTATION_FOLDER_SUCCESS";
export const DELETE_ICARUS_DOCUMENTATION_FOLDER_FAILED = "DELETE_ICARUS_DOCUMENTATION_FOLDER_FAILED";

export const GO_BACK_TO_FOLDER = "GO_BACK_TO_FOLDER";
export const GO_BACK_TO_ROOT_FOLDER = "GO_BACK_TO_ROOT_FOLDER";
export const CLEAR_FOLDERS  = "CLEAR_FOLDERS";
export const ENTER_FOLDER = "ENTER_FOLDER";
export const EXIT_FOLDER = "EXIT_FOLDER";

export const LOAD_ICARUS_DOCS_REQUEST = "LOAD_ICARUS_DOCS_REQUEST";
export const LOAD_ICARUS_DOCS_SUCCESS = "LOAD_ICARUS_DOCS_SUCCESS";
export const LOAD_ICARUS_DOCS_FAILED = "LOAD_ICARUS_DOCS_FAILED";

//DOCUMENTATION
export const LOAD_DOCUMENTATION_FOLDERS_FAILED = "LOAD_DOCUMENTATION_FOLDERS_FAILED";

export const LOAD_DOCUMENTATION_FOLDER_FOR_FILE_REQUEST = "LOAD_DOCUMENTATION_FOLDER_FOR_FILE_REQUEST";

export const LOAD_STORAGE_INFO_REQUEST = "LOAD_STORAGE_INFO_REQUEST";
export const LOAD_STORAGE_INFO_SUCCESS = "LOAD_STORAGE_INFO_SUCCESS";






